#!/bin/bash

# Colors ----------------
COLOR_STATUS_BAR_BG="colour235"
COLOR_STATUS_BAR_BG_INACTIVE="colour235"
COLOR_STATUS_BAR_FG="colour15"
COLOR_STATUS_BAR_FG_INACTIVE="colour243"
COLOR_TAB_ACTIVE_BG="colour064"
COLOR_TAB_ACTIVE_BG_INACTIVE="colour33"
COLOR_TAB_ACTIVE_FG="colour15"
COLOR_TAB_ACTIVE_FG_INACTIVE="colour15"
COLOR_BORDER_BG="default"
COLOR_BORDER_FG="colour34"
COLOR_BORDER_BG_INACTIVE="default"
COLOR_BORDER_FG_INACTIVE="colour33"
COLOR_CPU_LOAD_LOW="#[fg=colour064]"
COLOR_CPU_LOAD_MIDDLE="#[fg=colour208]"
COLOR_CPU_LOAD_HIGH="#[fg=colour196]"
