#!/bin/bash

# Styles ----------------
STYLE_STATUS_BAR="bg=$COLOR_STATUS_BAR_BG fg=$COLOR_STATUS_BAR_FG"
STYLE_LEFT="bg=$COLOR_STATUS_BAR_BG fg=$COLOR_STATUS_BAR_FG"
STYLE_RIGHT="bg=$COLOR_STATUS_BAR_BG fg=$COLOR_STATUS_BAR_FG"
STYLE_TAB="bg=$COLOR_STATUS_BAR_BG fg=$COLOR_STATUS_BAR_FG"
STYLE_TAB_ACTIVE="bg=$COLOR_TAB_ACTIVE_BG fg=$COLOR_TAB_ACTIVE_FG"
STYLE_STATUS_BAR_INACTIVE="bg=$COLOR_STATUS_BAR_BG_INACTIVE fg=$COLOR_STATUS_BAR_FG_INACTIVE"
STYLE_LEFT_INACTIVE="$STYLE_STATUS_BAR_INACTIVE"
STYLE_RIGHT_INACTIVE="$STYLE_STATUS_BAR_INACTIVE"
STYLE_TAB_INACTIVE="$STYLE_STATUS_BAR_INACTIVE"
STYLE_TAB_ACTIVE_INACTIVE="bg=$COLOR_TAB_ACTIVE_BG_INACTIVE fg=$COLOR_TAB_ACTIVE_FG_INACTIVE"

