#!/bin/bash

COLOR='\033[0;34m'
GREEN='\033[0;32m'

NC='\033[0m'


function getPlatform() {
    if [[ "$(uname)" == "Darwin" ]]; then
        echo "Darwin"
        return 0
        elif [[ "$(expr substr $(uname -s) 1 5)" == "Linux" ]]; then
        echo "Linux"
        return 0
    fi
    echo "Unkown"
}

function isDarwin() {
    platform=$(getPlatform)
    if [[ "$platform" == "Darwin" ]]; then
        echo true
        return 0
    fi
    echo false
}

function isLinux() {
    platform=$(getPlatform)
    if [[ "$platform" == "Linux" ]]; then
        echo true
        return 0
    fi
    echo false
}

CONTEXT="$(find-docker-context)"

if [[ "$(isLinux)" == true ]]; then
    DOCKER_BINARY="/usr/bin/docker"
else
    DOCKER_BINARY="/opt/homebrew/bin/docker"
fi

# use --context parameter is set
if [[ "$*" == *"--context"* ]]
then
    # printf "${COLOR}Overwrite context from parameter.${NC}\n"
    CONTEXT=""
else
    # printf "> Running in context ${COLOR}$CONTEXT${NC}\n"
    CONTEXT="--context $CONTEXT"
fi


# set -x
printf "> ${COLOR}docker ${GREEN}$CONTEXT${NC}${COLOR} $*${NC}\n"
$DOCKER_BINARY $CONTEXT "$@" # $CONTEXT "$@"
# set +x