#!/bin/bash

COLOR='\033[0;34m'
GREEN='\033[0;32m'

NC='\033[0m'

CONTEXT="$(find-docker-context)"

# use --context parameter is set
if [[ "$*" == *"--context"* ]]
then
    # printf "${COLOR}Overwrite context from parameter.${NC}\n"
    CONTEXT=""
else
    # printf "> Running in context ${COLOR}$CONTEXT${NC}\n"
    CONTEXT="--context $CONTEXT"
fi


# set -x
printf "> ${COLOR}docker ${GREEN}$CONTEXT${NC}${COLOR} $*${NC}\n"
/usr/bin/docker $CONTEXT "$@" # $CONTEXT "$@"
# set +x