DOTFILES_ROOT="$HOME/.dotfiles"

ZSH_ROOT="$DOTFILES_ROOT/zsh"
ZSH_STORAGE_ROOT="$ZSH_ROOT/.storage"
FLAG_ROOT="$ZSH_STORAGE_ROOT/flags"
OPTIONS_ROOT="$ZSH_STORAGE_ROOT/options"

ZSH_FLAG_CONFIG_ROOT="$ZSH_ROOT/flags"
ZSH_ALIASES_CONFIG_ROOT="$ZSH_ROOT/aliases"
ZSH_PLUGIN_ROOT="$ZSH_ROOT/plugins"

FLAG_RUNNER_PREFIX="_dot.flags"

ZSH_FLAG_EXT=".zsh.flag"
ZSH_FLAG_HANDLER_EXT=".flaghandler.zsh"




