DOTFILES_ROOT="$HOME/.dotfiles"

ZSH_ROOT="$DOTFILES_ROOT/zsh"
ZSH_STORAGE_ROOT="$ZSH_ROOT/.storage"
FLAG_ROOT="$ZSH_STORAGE_ROOT/flags"

ZSH_FLAG_CONFIG_ROOT="$ZSH_ROOT/flags"
ZSH_ALIASES_CONFIG_ROOT="$ZSH_ROOT/aliases"

HOST_CONFIG_ROOT="$ZSH_ROOT/host-config"

ZSH_FLAG_ALIAS_PREFIX="zsh.flag"
ZSH_FLAG_EXT=".zsh.flag"
ZSH_FLAG_HANDLER_EXT=".flaghandler.zsh"

TMUX_FLAG_ALIAS_PREFIX="tmux.flag"
TMUX_FLAG_EXT=".tmux.flag"



CHECK_EVERY_N_STARTUPS=10
